title = "CodeLab"
baseURL = "https://www.codelab.club/"
languageCode = "zh-cn"
theme = "airspace-hugo"

[menu]

  # 用于展示活动
  [[menu.header]]
   weight = 2
   name = "Events"
   url = "/work"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "/blog"
  # 用于列出都有什么可用的服务,最好是独立的页面 scratch3 adapter python mu
  [[menu.header]]
  weight = 2
  name = "Download"
  url = "/blog/codelab-download"
  # [[menu.header]]
  #   weight = 5
  #   name = "Contact"
  #   url = "/contact"
  [[menu.header]]
    weight = 4
    name = "About"
    url = "/about"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "/about"
  [[menu.footer]]
    weight = 2
    name = "CodeLab Adapter"
    url = "https://adapter.codelab.club/"
  # [[menu.footer]]
  #   weight = 3
  #   name = "How it works"
  #   url = "#"
  [[menu.footer]]
    weight = 3
    name = "Demo"
    url = "https://adapter.codelab.club/user_guide/gallery/"
  # [[menu.footer]]
  #   weight = 3
  #   name = "How it works"
  #   url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "/blog"
  
  [[menu.footer]]
    weight = 5
    name = "Download"
    url = "/blog/codelab-download"

  [[menu.footer]]
    weight = 6
    name = "Github"
    url = "https://github.com/codelabclub"

  [[menu.footer]]
    weight = 7
    name = "Insight"
    url = "http://insight.codelab.club:18000/"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "CodeLab"
    subtitle = "传递编程的乐趣，帮助孩子成为数字时代的创作者"

  [params.wrapper]
    enable = true
    title = "关于我们"
    # 致力于做什么
    # italic = "如果你想走得快，一个人走; 如果你想走得远，一群人走"
    paragraph = "CodeLab是一个非营利组织，致力于传递编程的乐趣，鼓励孩子成为数字时代的创作者；帮助他们理解和参与日益数字化的世界，使用编程表达自己的想法"

  # what why how

  # [params.blog]
  #   enable = true
  #   title = "我们准备怎么做"
  #   subtitle = "CodeLab将构建先进的少儿编程平台、活跃的用户社区以及丰富编程内容体系；构建可编程硬件、AI体系；输出内容给家庭、学校、机构；输出内容给其他教育类公益组织，构建多种层面的用户社区"

  [params.feature]
    enable = true
    # 价值观
    title = "我们准备怎么做"
    content = "线下方面，CodeLab将在全国主要城市，利用周末时间，组织志愿者、借用场地，开展编程活动；线上方面，CodeLab将构建先进的少儿编程平台，在积木化编程里加入开源硬件、物联网和人工智能；同时我们将构建活跃的用户社区，鼓励家长、教育者、学习者参与其中；我们也乐于与其他公益组织展开合作，让编程与更广泛的社会活动结合"

    #[params.feature.button]
    #  caption = "View Works"
    #  url = "#"

  [params.call]
    enable = true
    # 出现在各种地方 4P
    # title = "4P"
    # Imagine, Program, Share
    paragraph = "Projects, Passion, Peers, Play"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    # [params.contact.form]
    #   name = "Your name"
    #   email = "Your email"
    #   subject = "Your subject"
    #   message = "Your message"
    #   button = "Send message"
    [params.contact.box]
      title = "联系我们"
      # address = "North Main Street, Brooklyn Australia"
      email = "Email: wuwenjie@codelab.club"
      # phone = "Phone: +88 01672 506 744"
    #[params.contact.gmaps]
    #  enable = false
    #  title = "We Also Count in Google Maps"

[markup]
  defaultMarkdownHandler = "blackfriday"
